//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int Id { get; set; }
        public Nullable<int> UseriId { get; set; }
        public Nullable<int> TeklifId { get; set; }
        public string UserNot { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Teklif Teklif { get; set; }
        public virtual User User { get; set; }
    }
}
