//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teklif
    {
        public int Id { get; set; }
        public string Firma { get; set; }
        public Nullable<int> TeklifNo { get; set; }
        public Nullable<int> StokId { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> Birim { get; set; }
        public Nullable<int> Tutar { get; set; }
        public Nullable<int> CariId { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public Nullable<int> KarOrani { get; set; }
        public Nullable<int> Kar { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual CariKartlar CariKartlar { get; set; }
        public virtual Proje Proje { get; set; }
        public virtual StokKartlar StokKartlar { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }

     
    }
}
